[package]
name = "reth-bench-compare"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "reth-bench-compare"
path = "src/main.rs"

[dependencies]
# CLI and argument parsing
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true

# Async runtime
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

# Serialization (still needed for JSON handling)
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

# Process management
ctrlc = "3.4"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["signal", "process"] }

# Time handling
chrono = "0.4"

# Path manipulation
shellexpand.workspace = true

# CSV handling for results comparison
csv.workspace = true

# Reth dependencies for shared types and utilities
reth-tracing.workspace = true
reth-cli-runner.workspace = true
reth-node-core.workspace = true
reth-cli-util.workspace = true
reth-chainspec.workspace = true

# Alloy for RPC communication
alloy-provider = { workspace = true, features = ["reqwest", "reqwest-rustls-tls"] }
alloy-rpc-types-eth = { workspace = true }
