[package]
name = "reth-mdbx-sys"
description = "Raw bindings for libmdbx"
version.workspace = true
edition = "2021"
rust-version.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true

[build-dependencies]
cc.workspace = true
bindgen = { workspace = true, features = ["runtime"] }
